package com.qwerys.qwerys_backend.analyzer.procedural;

import com.qwerys.qwerys_backend.analyzer.AstNode;
import com.qwerys.qwerys_backend.analyzer.SemanticError;
import com.qwerys.qwerys_backend.analyzer.SqlServerDialectAnalyzer;

import java.util.List;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * T-SQL–specific procedural rules for SQL Server stored code.
 */
public class TSqlAnalyzer extends SqlServerDialectAnalyzer {

    private static final Pattern CREATE_PROC =
            Pattern.compile("\\bCREATE\\s+(?:OR\\s+ALTER\\s+)?(?:PROC|PROCEDURE)\\b",
                    Pattern.CASE_INSENSITIVE);

    private static final Pattern SET_NOCOUNT_ON =
            Pattern.compile("\\bSET\\s+NOCOUNT\\s+ON\\b", Pattern.CASE_INSENSITIVE);

    private static final Pattern BEGIN_TRY =
            Pattern.compile("\\bBEGIN\\s+TRY\\b", Pattern.CASE_INSENSITIVE);

    private static final Pattern BEGIN_CATCH =
            Pattern.compile("\\bBEGIN\\s+CATCH\\b", Pattern.CASE_INSENSITIVE);

    private static final Pattern RAISERROR_KW =
            Pattern.compile("\\bRAISERROR\\s*\\(", Pattern.CASE_INSENSITIVE);

    private static final Pattern CURSOR_OPEN =
            Pattern.compile("\\bOPEN\\s+(\\w+)\\b", Pattern.CASE_INSENSITIVE);

    private static final Pattern TABLE_VAR_IN_JOIN =
            Pattern.compile(
                    "(?is)(?:JOIN|FROM)[^;\\n]+?(@\\w+)|(@\\w+)[^;\\n]*?\\bJOIN\\b",
                    Pattern.CASE_INSENSITIVE);

    private static final Pattern GOTO_KW =
            Pattern.compile("\\bGOTO\\s+\\w+", Pattern.CASE_INSENSITIVE);

    private static final Pattern SELECT_STAR_INTO_HASH =
            Pattern.compile("\\bSELECT\\s+\\*\\s+INTO\\s+#\\w+", Pattern.CASE_INSENSITIVE);

    private static final Pattern WAITFOR_DELAY =
            Pattern.compile("(?is)\\bWAITFOR\\s+DELAY\\s+'([^']+)'");

    private static final Pattern SP_EXECUTESQL =
            Pattern.compile("\\bsp_executesql\\b", Pattern.CASE_INSENSITIVE);

    private static final Pattern SP_EXECUTESQL_HAS_PARAM_LIST =
            Pattern.compile("(?is)sp_executesql\\s*\\([^)]*,");

    private static final Pattern IDENTITY_ATAT =
            Pattern.compile("@@IDENTITY\\b", Pattern.CASE_INSENSITIVE);

    private static final Pattern JOIN_COUNT =
            Pattern.compile("\\bJOIN\\b", Pattern.CASE_INSENSITIVE);

    public TSqlAnalyzer(AstNode root, String rawSql) {
        this(root, rawSql, Locale.ENGLISH);
    }

    public TSqlAnalyzer(AstNode root, String rawSql, Locale uiLocale) {
        super(root, rawSql, uiLocale != null ? uiLocale : Locale.ENGLISH);
    }

    @Override
    protected void analyzeDialectSpecific(List<SemanticError> errors) {
        super.analyzeDialectSpecific(errors);
        if (rawSql == null || rawSql.isBlank()) {
            return;
        }
        checkProcSs001(errors);
        checkProcSs002(errors);
        checkProcSs003(errors);
        checkProcSs004(errors);
        checkProcSs005(errors);
        checkProcSs006(errors);
        checkProcSs007(errors);
        checkProcSs009(errors);
        checkProcSs010(errors);
    }

    @Override
    protected void checkAtAtIdentity(List<SemanticError> errors) {
        if (!rawSqlMatches(IDENTITY_ATAT)) {
            return;
        }
        errors.add(new SemanticError(
                "PROC-SS-008",
                t("@@IDENTITY may return IDs generated by triggers, not just the current statement",
                        "@@IDENTITY puede devolver IDs generados por triggers, no solo por la sentencia actual"),
                t("Same as rule SS007: use SCOPE_IDENTITY() for the local statement scope.",
                        "Mismo hallazgo que la regla SS007: usa SCOPE_IDENTITY() para el ámbito local de la sentencia."),
                SemanticError.Severity.WARNING));
    }

    private void checkProcSs001(List<SemanticError> errors) {
        if (!CREATE_PROC.matcher(rawSql).find()) {
            return;
        }
        if (SET_NOCOUNT_ON.matcher(rawSql).find()) {
            return;
        }
        errors.add(new SemanticError(
                "PROC-SS-001",
                t("Procedure without SET NOCOUNT ON", "Procedimiento sin SET NOCOUNT ON"),
                t("Add SET NOCOUNT ON at the start to reduce @@ROWCOUNT message traffic per statement.",
                        "Añade SET NOCOUNT ON al inicio para reducir tráfico de mensajes @@ROWCOUNT por sentencia."),
                SemanticError.Severity.INFO));
    }

    private void checkProcSs002(List<SemanticError> errors) {
        if (!BEGIN_TRY.matcher(rawSql).find()) {
            return;
        }
        if (BEGIN_CATCH.matcher(rawSql).find()) {
            return;
        }
        errors.add(new SemanticError(
                "PROC-SS-002",
                t("BEGIN TRY without matching BEGIN CATCH", "BEGIN TRY sin BEGIN CATCH correspondiente"),
                t("Each TRY block in T-SQL must be followed by BEGIN CATCH…END CATCH.",
                        "Cada bloque TRY en T-SQL debe ir seguido de BEGIN CATCH…END CATCH."),
                SemanticError.Severity.ERROR));
    }

    private void checkProcSs003(List<SemanticError> errors) {
        if (!RAISERROR_KW.matcher(rawSql).find()) {
            return;
        }
        errors.add(new SemanticError(
                "PROC-SS-003",
                t("RAISERROR (legacy form) detected", "RAISERROR (forma legacy) detectada"),
                t("In SQL Server 2012+, consider THROW for consistent rethrow and messages.",
                        "En SQL Server 2012+, considera THROW para rethrow y mensajes consistentes."),
                SemanticError.Severity.INFO));
    }

    private void checkProcSs004(List<SemanticError> errors) {
        String low = rawSql.toLowerCase(Locale.ROOT);
        if (!low.contains("cursor")) {
            return;
        }
        Matcher openM = CURSOR_OPEN.matcher(rawSql);
        while (openM.find()) {
            String name = openM.group(1);
            Matcher deall = Pattern.compile(
                    "\\bDEALLOCATE\\s+" + Pattern.quote(name) + "\\b",
                    Pattern.CASE_INSENSITIVE).matcher(rawSql);
            if (!deall.find()) {
                errors.add(new SemanticError(
                        "PROC-SS-004",
                        t("OPEN " + name + " without DEALLOCATE", "OPEN " + name + " sin DEALLOCATE"),
                        t("Release the session cursor with DEALLOCATE " + name + ".",
                                "Libera el cursor en sesión con DEALLOCATE " + name + "."),
                        SemanticError.Severity.WARNING));
            }
        }
    }

    private void checkProcSs005(List<SemanticError> errors) {
        int joins = 0;
        Matcher jm = JOIN_COUNT.matcher(rawSql);
        while (jm.find()) {
            joins++;
        }
        if (joins < 3) {
            return;
        }
        Matcher m = TABLE_VAR_IN_JOIN.matcher(rawSql);
        while (m.find()) {
            String v = m.group(1) != null ? m.group(1) : m.group(2);
            if (v != null && v.startsWith("@")) {
                errors.add(new SemanticError(
                        "PROC-SS-005",
                        t("Table variable " + v + " in query with multiple JOINs",
                                "Variable de tabla " + v + " en consulta con varios JOINs"),
                        t("Consider a #temp table when exceeding ~1000 rows or complex plans.",
                                "Considera una tabla temporal (#temp) cuando superas ~1000 filas o planes complejos."),
                        SemanticError.Severity.WARNING));
                return;
            }
        }
    }

    private void checkProcSs006(List<SemanticError> errors) {
        if (!GOTO_KW.matcher(rawSql).find()) {
            return;
        }
        errors.add(new SemanticError(
                "PROC-SS-006",
                t("GOTO detected", "GOTO detectado"),
                t("Refactor to structured control flow (IF/WHILE/TRY) instead of jumps.",
                        "Refactoriza con control flow estructurado (IF/WHILE/TRY) en lugar de saltos."),
                SemanticError.Severity.WARNING));
    }

    private void checkProcSs007(List<SemanticError> errors) {
        if (!SELECT_STAR_INTO_HASH.matcher(rawSql).find()) {
            return;
        }
        errors.add(new SemanticError(
                "PROC-SS-007",
                t("SELECT * INTO #temp", "SELECT * INTO #temp"),
                t("List columns explicitly to avoid hidden dependencies when the source schema changes.",
                        "Especifica columnas para evitar dependencias ocultas cuando cambia el esquema origen."),
                SemanticError.Severity.WARNING));
    }

    private void checkProcSs009(List<SemanticError> errors) {
        Matcher m = WAITFOR_DELAY.matcher(rawSql);
        while (m.find()) {
            String time = m.group(1);
            if (longDelay(time)) {
                errors.add(new SemanticError(
                        "PROC-SS-009",
                        t("Long WAITFOR DELAY ('" + time + "')", "WAITFOR DELAY largo ('" + time + "')"),
                        t("Blocks the worker connection until the delay expires.",
                                "Bloquea la conexión de trabajo hasta que expire el retraso."),
                        SemanticError.Severity.WARNING));
                return;
            }
        }
    }

    /** Acepta patrones tipo {@code '00:00:15'} o {@code '0:15:0'}. */
    private static boolean longDelay(String timeSpec) {
        if (timeSpec == null) {
            return false;
        }
        String[] parts = timeSpec.trim().split(":");
        try {
            if (parts.length == 3) {
                int h = Integer.parseInt(parts[0].replaceFirst("^0+(?!$)", ""));
                int mi = Integer.parseInt(parts[1].replaceFirst("^0+(?!$)", ""));
                int s = Integer.parseInt(parts[2].replaceFirst("^0+(?!$)", ""));
                return h > 0 || mi >= 1 || s >= 10;
            }
            if (parts.length == 1) {
                return Integer.parseInt(parts[0]) >= 10;
            }
        } catch (NumberFormatException ignored) {
            return true;
        }
        return false;
    }

    private void checkProcSs010(List<SemanticError> errors) {
        if (!SP_EXECUTESQL.matcher(rawSql).find()) {
            return;
        }
        if (SP_EXECUTESQL_HAS_PARAM_LIST.matcher(rawSql).find()) {
            return;
        }
        errors.add(new SemanticError(
                "PROC-SS-010",
                t("sp_executesql with dynamic SQL without explicit parameter list",
                        "sp_executesql con SQL dinámico sin lista de parámetros explícita"),
                t("SQL injection risk: use sp_executesql @stmt, N'@p int', @p with bound parameters.",
                        "Riesgo de SQL injection: usa la forma sp_executesql @stmt, N'@p int', @p con parámetros enlazados."),
                SemanticError.Severity.ERROR));
    }
}
